import Head from "next/head";
import { Footer } from "../components/footer";
import { Navbar } from "../components/navbar";
import AboutUsSection from "./components/AboutUs";
import Mission from "./components/Mission";
import TeamCards from "./components/TeamCards";
import Vision from "./components/Vision";

const About = () => {
  return (
    <>
      <Head>
        <title>About Us | Ikiguys</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/" />
      </Head>

      <Navbar />
      <AboutUsSection />
      <Mission />
      <Vision />
      <TeamCards />
      <Footer />
    </>
  );
};

export default About;
